### ISSUE TITLE
JSON Recipes client crash

### ISSUE THREAD

**Issue by Thronk** [QMXTech/Numina#2] opened 2015-01-19 19:36 UTC
Using the latest versions MPS 0.11.0.5-QMX and Numina 0.4.0.4-QMX and previous versions give this client crash when clicking in NEI for recipe on any Modular Power suits recipes.

http://pastebin.com/azm3mvN6

This is with both thermal expansion and vanilla recipes in the recipe folder. Without it simply doesn't do anything when clicking for recipe.

This the second day I'm troubleshooting this issue trying to put a custom modpack together. The Direwolf20 1.7.10 modpack on FTB doesn't seem to have this issue and I even tried copying those files over with no success.
So I'm not sure where the problem lies, whether it's in some libraries, forge or NEI.

**Comment by Korynkai** [comment] 2015-01-19 20:21
How strange... Also you say 0.4.0.4-QMX? This version was removed from download due to API changes regarding sounds. These changes themselves could cause your client to crash, though this specific crash is caused by an error in either a recipe file or the JSON handler (which I'll be working on anyway this upcoming release) ... Please ensure this crash continues to occur with all the files located here: https://github.com/QMXTech/MachineMusePowersuits/releases/tag/0.11.0.5-QMX , especially Numina 0.4.0.5-QMX and the recipe files.

**Comment by Thronk** [comment] 2015-01-20 00:57
I tried with the files you mentioned and still the same. I was using Cauldron and tried just forge, also same (both version of forge 1240).

Here is the powersuits.cfg that it generates: http://pastebin.com/DfQGfc1G
Crashlog is the same.

I tried with both recipe files (vanilla and thermal expansion) in the recipe folders on both client and server. Then without and with only vanilla, then with only on server side. All same results except when there's no recipe file then it just doesn't do anything.

**Comment by Thronk** [comment] 2015-01-26 18:19
Just want to add that pressing U or right clicking on any item, doesn't have to be one from MPS mod, will generate this crash report. http://pastebin.com/4aTcqZSx
It's seems to be the same as the previous one I posted, more or less.

**Comment by Korynkai** [comment] 2015-01-29 01:18
Finally fixed internally. However I cannot release Numina 0.4.0.6-QMX until Jörg Haeger returns my email authorizing the relicensing of OggAudioData to LGPL.

**Comment by Thronk** [comment] 2015-01-29 16:46
Fixed on next release build? It's still producing client crashes.

**Comment by Korynkai** [comment] 2015-02-14 09:29
Released.

**Closed by Korynkai** 2015-02-14 09:29 UTC
Labels: Code Finished (In Git)
